from ui.components.button import Button
from core.constants import *

login_button = Button(LOGIN_BUTTON_X, LOGIN_BUTTON_Y, LOGIN_BUTTON_WIDTH, LOGIN_BUTTON_HEIGHT)
move_to_signup_button = Button(MOVE_TO_SIGNUP_BUTTON_X, MOVE_TO_SIGNUP_BUTTON_Y, MOVE_TO_SIGNUP_BUTTON_WIDTH, MOVE_TO_SIGNUP_BUTTON_HEIGHT)
username_input = Button(LOGIN_USERNAME_X, LOGIN_USERNAME_Y, LOGIN_INPUT_WIDTH, LOGIN_INPUT_HEIGHT)
password_input = Button(LOGIN_PASSWORD_X, LOGIN_PASSWORD_Y, LOGIN_INPUT_WIDTH, LOGIN_INPUT_HEIGHT)

aerobics_button = Button(AEROBICS_BUTTON_X, AEROBICS_BUTTON_Y, AEROBICS_BUTTON_WIDTH, AEROBICS_BUTTON_HEIGHT)
strength_button = Button(STRENGTH_BUTTON_X, STRENGTH_BUTTON_Y, AEROBICS_BUTTON_WIDTH, AEROBICS_BUTTON_HEIGHT)
shop_button = Button(SHOP_BUTTON_X, SHOP_BUTTON_Y, SHOP_BUTTON_WIDTH, SHOP_BUTTON_HEIGHT)
shop_back_button = Button(SHOP_BACK_BUTTON_X, SHOP_BACK_BUTTON_Y, SHOP_BACK_BUTTON_WIDTH, SHOP_BACK_BUTTON_HEIGHT)
